### ISSUE TITLE
Add screenshot to README.md

### ISSUE THREAD

**Issue by evetion** [JuliaGeo/Leaflet.jl#11]
As a picture is a thousand words ;)

**Comment by rafaqz** [comment]
Absolutely, maybe a screenshot of the example

**Comment by evetion** [comment]
Fixed by https://github.com/JuliaGeo/Leaflet.jl/commit/303911ce1f923553dcf2870a158cd82205c03faa.

**Comment by rafaqz** [comment]
Glad you did it that looks so much slicker than my crappy linux screenshots
